version: '3.12.0'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
